### ISSUE TITLE
Проблема с запуском и парсингом.

### ISSUE THREAD

**Issue by RemMajiTensh1** [Oleksandrigo/ranobelibParser#7]
Изначально была проблема с тем что не работали модули.
После установки модулей по новой появилась проблема с дескриптором.
```
Traceback (most recent call last):
  File "C:\Users\ADMEEN\Desktop\ranobelibParser-master\main.py", line 169, in <module>
    start_parse(input_url)
  File "C:\Users\ADMEEN\Desktop\ranobelibParser-master\main.py", line 146, in start_parse
    main_title = browser.find_element(by=By.XPATH,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ADMEEN\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ADMEEN\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\ADMEEN\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[3]/div/div/div/div[2]/div[1]/div[1]/div[1]"}
  (Session info: chrome=125.0.6422.78); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
        GetHandleVerifier [0x004EB793+45827]
        (No symbol) [0x0047DB74]
        (No symbol) [0x0037150F]
        (No symbol) [0x003B20BC]
        (No symbol) [0x003B216B]
        (No symbol) [0x003EE0F2]
        (No symbol) [0x003D2E44]
        (No symbol) [0x003EC034]
        (No symbol) [0x003D2B96]
        (No symbol) [0x003A6998]
        (No symbol) [0x003A751D]
        GetHandleVerifier [0x007A43C3+2899763]
        GetHandleVerifier [0x007F77ED+3240797]
        GetHandleVerifier [0x00571264+593364]
        GetHandleVerifier [0x0057818C+621820]
        (No symbol) [0x00486F54]
        (No symbol) [0x00483658]
        (No symbol) [0x004837F7]
        (No symbol) [0x004758AE]
        BaseThreadInitThunk [0x74D8FCC9+25]
        RtlGetAppContainerNamedObjectPath [0x76EF7CBE+286]
        RtlGetAppContainerNamedObjectPath [0x76EF7C8E+238]

Exception ignored in: <function Chrome.__del__ at 0x00000211A8A89260>
Traceback (most recent call last):
  File "C:\Users\ADMEEN\AppData\Local\Programs\Python\Python312\Lib\site-packages\undetected_chromedriver\__init__.py", line 843, in __del__
  File "C:\Users\ADMEEN\AppData\Local\Programs\Python\Python312\Lib\site-packages\undetected_chromedriver\__init__.py", line 798, in quit
OSError: [WinError 6] Неверный дескриптор
```

**Comment by Oleksandrigo** [comment]
Опишите как проходит процесс от начала запуска батника и до вылета

**Comment by RemMajiTensh1** [comment]
закидываю ссылку
открывается браузер
ничего не жму не двигаю
закрывается браузер
вылетает ошибка в cmd

**Comment by Oleksandrigo** [comment]
А в браузере что происходит?

**Comment by KoksMen** [comment]
Лично у меня при запуске батника просто пишет "Python Нажмите любую кнопку для продолжения", после нажатию просто закрывается

**Comment by louisefag** [comment]
Та же проблема. Открывается окно хрома, пару секунд висит на главной ранобелиба и закрывается с ошибками теми же.
